version: "3"

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
