version: "3"

services:
  template-app:
    container_name: template-app
    build:
      context: .
      dockerfile: ./apps/template-app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
