# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:

# TODO: Add a job to install and cache npm dependencies. NOTE: Switch from using yarn and yarn-cache to npm (or pnpm). Makre sure other jobs use the same package manager.
# # Install and cache npm dependencies
#   install-cache:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Commit
#         uses: actions/checkout@v2
#       - name: Cache yarn dependencies and cypress
#         uses: actions/cache@v2
#         id: yarn-cache
#         with:
#           path: |
#             ~/.cache/Cypress
#             node_modules
#           key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-v1
#       - name: Install dependencies if cache invalid
#         if: steps.yarn-cache.outputs.cache-hit != 'true'
#         run: yarn

  # Job name
  # # Run visual and composition tests with Chromatic
  # visual-and-composition:
  #   runs-on: ubuntu-latest
  #   needs: install-cache
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 # Required to retrieve git history
  #     - name: Restore yarn dependencies
  #       uses: actions/cache@v2
  #       id: yarn-cache
  #       with:
  #         path: |
  #           ~/.cache/Cypress
  #           node_modules
  #         key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-v1
  #     - name: Publish to Chromatic
  #       uses: chromaui/action@v1
  #       with:
  #         # Grab this from the Chromatic manage page
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # TODO: Add a job to run your integration tests
#  # Run interaction and accessibility tests
#   interaction-and-accessibility:
#     runs-on: ubuntu-latest
#     needs: install-cache
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '16.x'
#       - name: Restore yarn dependencies
#         uses: actions/cache@v2
#         id: yarn-cache
#         with:
#           path: |
#             ~/.cache/Cypress
#             node_modules
#           key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-v1
#       - name: Install Playwright
#         run: npx playwright install --with-deps
#       - name: Build Storybook
#         run: yarn build-storybook --quiet
#       - name: Serve Storybook and run tests
#         run: |
#           npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
#             "npx http-server storybook-static --port 6006 --silent" \
#             "npx wait-on tcp:6006 && yarn test-storybook"

  # TODO: Run user flow tests with Cypress
  # # Job name
  # user-flow:
  #   runs-on: ubuntu-latest
    # needs: install-cache
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       with:
  #         start: npm run dev
