# .github/workflows/storybook-tests.yml

name: 'Storybook Tests'

on:
  push:
    # Only run when there are changes to the storybook directory
    paths:
      - 'packages/acme-storybook/**'
      - 'packages/acme-design-system/**'
jobs:
  test-storybook:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: ./packages/acme-storybook

      - name: Build Storybook
        run: pnpm build-storybook --quiet
        working-directory: ./packages/acme-storybook

      - name: Serve Storybook and run tests
        run: pnpm test # NOTE: This will run the test script which also runs the http server for Storybook
        working-directory: ./packages/acme-storybook
